### ISSUE TITLE
Lang problem

### ISSUE THREAD

**Issue by ElMoha943** [TownyAdvanced/TownyCombat#21]
Using English (default) lang in TownyCombat and Spanish in Towny

```
12.04 12:49:28 [Server] INFO ValenGamerXD issued server command: /tcm reload
12.04 12:49:28 [Server] INFO Successfully loaded translations for 0 languages.
12.04 12:49:28 [Server] INFO Loaded additional language files for plugin: TownyCombat
12.04 12:49:28 [Server] ERROR null
12.04 12:49:28 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'tcm' in plugin TownyCombat v0.2.0
12.04 12:49:28 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
12.04 12:49:28 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
12.04 12:49:28 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905) ~[purpur-1.18.2.jar:git-Purpur-1609]
12.04 12:49:28 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2389) ~[?:?]
12.04 12:49:28 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2200) ~[?:?]
12.04 12:49:28 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2181) ~[?:?]
12.04 12:49:28 [Server] INFO at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
12.04 12:49:28 [Server] INFO at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
12.04 12:49:28 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
12.04 12:49:28 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1609]
12.04 12:49:28 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
12.04 12:49:28 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
12.04 12:49:28 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[purpur-1.18.2.jar:git-Purpur-1609]
12.04 12:49:28 [Server] INFO at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1609]
12.04 12:49:28 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
12.04 12:49:28 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1403) ~[purpur-1.18.2.jar:git-Purpur-1609]
12.04 12:49:28 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1396) ~[purpur-1.18.2.jar:git-Purpur-1609]
12.04 12:49:28 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
12.04 12:49:28 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1530) ~[purpur-1.18.2.jar:git-Purpur-1609]
12.04 12:49:28 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.18.2.jar:git-Purpur-1609]
12.04 12:49:28 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1609]
12.04 12:49:28 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
12.04 12:49:28 [Server] INFO Caused by: java.lang.StackOverflowError
12.04 12:49:28 [Server] INFO at com.palmergames.bukkit.towny.object.Translation.of(Translation.java:86) ~[towny-0.98.1.6.jar:?]
12.04 12:49:28 [Server] INFO at com.palmergames.bukkit.towny.object.Translation.of(Translation.java:125) ~[towny-0.98.1.6.jar:?]
12.04 12:49:38 [Multicraft] Skipped 1022 lines due to rate limit (30/s)
```

**Comment by ElMoha943** [comment]
[latest.log](https://github.com/TownyAdvanced/TownyCombat/files/8475142/latest.log)

**Comment by LlmDl** [comment]
So even when TownyCombat is first loading it is loading 0 language strings:
```
[13:28:10] [Server thread/INFO]: [TownyCombat] Towny version 0.98.1.6 found.
[13:28:10] [Server thread/INFO]: [TownyCombat] Successfully loaded translations for 0 languages.
[13:28:10] [Server thread/INFO]: [Towny] Loaded additional language files for plugin: TownyCombat
[13:28:10] [Server thread/INFO]: [TownyCombat] TownyCombat Enabled.
```

**Comment by LlmDl** [comment]
This was caused by Towny being told to ignore any locale except es-ES.

**Comment by Aisponch** [comment]
the same problem, but I also ignore es-ES. How do I find out the right language at all?

**Comment by ElMoha943** [comment]
> the same problem, but I also ignore es-ES. How do I find out the right language at all?

Problem happens when you ignore En lang as it is the default one

**Comment by Aisponch** [comment]
and how to remove ignoring?

**Comment by ElMoha943** [comment]
> and how to remove ignoring?

enabled_languages: '*'
