### ISSUE TITLE
Could not pass event EntityMountEvent to TownyCombat v0.3.0

### ISSUE THREAD

**Issue by EmptyEgo** [TownyAdvanced/TownyCombat#65]
```11.10 20:10:10 [Server] Server thread/ERROR Could not pass event EntityMountEvent to TownyCombat v0.3.0
11.10 20:10:10 [Server] INFO org.bukkit.event.EventException: null
11.10 20:10:10 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
11.10 20:10:10 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
11.10 20:10:10 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
11.10 20:10:10 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
11.10 20:10:10 [Server] INFO at net.minecraft.world.entity.Entity.addPassenger(Entity.java:2230) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
11.10 20:10:10 [Server] INFO at net.minecraft.world.entity.Entity.a(Entity.java:2161) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
11.10 20:10:10 [Server] INFO at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:1295) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
11.10 20:10:10 [Server] INFO at net.minecraft.world.entity.Entity.k(Entity.java:2135) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
11.10 20:10:10 [Server] INFO at net.minecraft.world.entity.animal.horse.EntityHorseAbstract.e(EntityHorseAbstract.java:523) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
11.10 20:10:10 [Server] INFO at net.minecraft.world.entity.animal.horse.EntityLlamaTrader.e(EntityLlamaTrader.java:71) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
11.10 20:10:10 [Server] INFO at net.minecraft.world.entity.animal.horse.EntityHorseChestedAbstract.b(SourceFile:208) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
11.10 20:10:10 [Server] INFO at net.minecraft.world.entity.EntityInsentient.a(EntityInsentient.java:1224) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
11.10 20:10:10 [Server] INFO at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:1112) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
11.10 20:10:10 [Server] INFO at net.minecraft.server.network.PlayerConnection$4.performInteraction(PlayerConnection.java:2546) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
11.10 20:10:10 [Server] INFO at net.minecraft.server.network.PlayerConnection$4.a(PlayerConnection.java:2565) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
11.10 20:10:10 [Server] INFO at net.minecraft.network.protocol.game.PacketPlayInUseEntity$d.a(SourceFile:116) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
11.10 20:10:10 [Server] INFO at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(SourceFile:66) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
11.10 20:10:10 [Server] INFO at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2510) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
11.10 20:10:10 [Server] INFO at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(SourceFile:53) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
11.10 20:10:10 [Server] INFO at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(SourceFile:13) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
11.10 20:10:10 [Server] INFO at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
11.10 20:10:10 [Server] INFO at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
11.10 20:10:10 [Server] INFO at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
11.10 20:10:10 [Server] INFO at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
11.10 20:10:10 [Server] INFO at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
11.10 20:10:10 [Server] INFO at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
11.10 20:10:10 [Server] INFO at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
11.10 20:10:10 [Server] INFO at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
11.10 20:10:10 [Server] INFO at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
11.10 20:10:10 [Server] INFO at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
11.10 20:10:10 [Server] INFO at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1106) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
11.10 20:10:10 [Server] INFO at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1017) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
11.10 20:10:10 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
11.10 20:10:10 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?]
11.10 20:10:10 [Server] INFO Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because the return value of "java.util.Map.get(Object)" is null
11.10 20:10:10 [Server] INFO at io.github.townyadvanced.townycombat.utils.TownyCombatMovementUtil.adjustMountWalkSpeed(TownyCombatMovementUtil.java:137) ~[?:?]
11.10 20:10:10 [Server] INFO at io.github.townyadvanced.townycombat.utils.TownyCombatMovementUtil.adjustPlayerAndMountSpeeds(TownyCombatMovementUtil.java:50) ~[?:?]
11.10 20:10:10 [Server] INFO at io.github.townyadvanced.townycombat.listeners.TownyCombatBukkitEventListener.on(TownyCombatBukkitEventListener.java:87) ~[?:?]
11.10 20:10:10 [Server] INFO at jdk.internal.reflect.GeneratedMethodAccessor449.invoke(Unknown Source) ~[?:?]
11.10 20:10:10 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
11.10 20:10:10 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
11.10 20:10:10 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
11.10 20:10:10 [Server] INFO ... 33 more
```

**Comment by LlmDl** [comment]
Need your config

**Comment by EmptyEgo** [comment]
It's been a long time since this was submit - you can close the ticket.

Thank you!
